---
- pip:
    name: docker-py

- name: Create a ext4 filesystem on attached volume
  filesystem:
    fstype: ext4
    dev: /dev/nvme1n1
    opts: -L GOCD_DB

- name: Create directory for GoCD data mount
  file:
    path: /var/gocd-data
    state: directory

- name: Mount GoCD volume by label
  mount:
    path: /var/gocd-data
    src: LABEL=GOCD_DB
    fstype: ext4
    state: mounted

- name: Set GoCD data directory permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: root
  with_items:
    - /var/gocd-data/data
    - /var/gocd-data/home
    - /var/gocd-data/data/config
    - /var/gocd-data/data/plugins/external

- name: Configure Google Chat plugin
  template:
    src: gchat_notif.conf.j2
    dest: /var/gocd-data/home/gchat_notif.conf

- name: Configure a properties file on the GoCD server container
  template:
    src: db.properties-template.j2
    dest: /var/gocd-data/data/config/db.properties
    owner: "{{ ansible_user }}"
    group: root
    mode: 0644

- name: Install gcc package
  yum:
    name: gcc

- name: Install postgresql-devel package
  yum:
    name: postgresql-devel

- name: Install psycopg2 python package
  pip:
    name: psycopg2

- name: Create the main db
  postgresql_db:
    name: gocd
    owner: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    login_host: "{{ db_url }}"
    encoding: UTF8
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'

- name: Create the analytics db
  postgresql_db:
    name: gocd_analytics
    owner: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    login_host: "{{ db_url }}"
    encoding: UTF8
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'

- name: Install analytics plugin
  get_url:
    url: https://github.com/gocd/gocd-analytics-plugin/releases/download/v3.0.0-5/gocd-analytics-plugin-3.0.0-5.jar
    dest: /var/gocd-data/data/plugins/external/gocd-analytics-plugin-3.0.0-5.jar

- name: Setup GoCD server container
  docker_container:
    name: server
    image: gocd/gocd-server:v20.10.0
    restart_policy: always
    restart: yes
    ports:
     - "8153:8153"
     - "8154:8154"
    env:
      GCHAT_NOTIFIER_CONF_PATH: /home/go/gchat_notif.conf
    volumes:
      - /var/gocd-data/data:/godata
      - /var/gocd-data/home:/home/go
