#!/bin/bash

set -Eeo pipefail

NHS_SERVICE=gocd
AWS_REGION=eu-west-2
AWS_DEFAULT_REGION=$AWS_REGION
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

function create_build_trace_id {
  if [ -z $GO_PIPELINE_NAME ]; then
    export BUILD_TRACE_ID=local
  else
    git_hash=$(echo $GO_REVISION_GIT | cut -c 1-8)
    export BUILD_TRACE_ID="gocd@$GO_PIPELINE_NAME@$GO_PIPELINE_COUNTER@$GO_STAGE_NAME@$GO_STAGE_COUNTER@$GO_JOB_NAME@$git_hash"
  fi
}

create_build_trace_id

function _get_aws_ssm_secret {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

function tf_plan {
  operation=$1

  my_ip=$(curl icanhazip.com)
  echo "Running terraform plan with added security group ingress from $my_ip"

  cd terraform/
  terraform init -reconfigure -backend-config key=nhs-${NHS_SERVICE}-${GOCD_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var my_ip=$my_ip -var-file=${GOCD_ENVIRONMENT}.tfvars -out="${NHS_SERVICE}-${GOCD_ENVIRONMENT}.tfplan" $2
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var my_ip=$my_ip -var-file=${GOCD_ENVIRONMENT}.tfvars -out="${NHS_SERVICE}-${GOCD_ENVIRONMENT}.tfplan" $2 -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  cd terraform/
  terraform init -backend-config key=nhs-${NHS_SERVICE}-${GOCD_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  terraform apply ${NHS_SERVICE}-${GOCD_ENVIRONMENT}.tfplan
  terraform output -json > tf-out-${GOCD_ENVIRONMENT}.json
}

function check_gocd_env {
  if [[ -z "${GOCD_ENVIRONMENT}" ]]; then
    echo "Must set GOCD_ENVIRONMENT"
    exit 1
  fi
}

function check_nhs_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function generate_ssh_key {
  secret_id="/repo/${GOCD_ENVIRONMENT}/user-input/gocd-id-rsa"
  mkdir -p terraform/ssh/
  if [[ ! -f "terraform/ssh/gocd-${GOCD_ENVIRONMENT}" ]]; then
    #TODO check aws authentication
    set +e
    id_rsa=$(aws ssm get-parameter --with-decryption --region $AWS_REGION --name $secret_id | jq -r ".Parameter.Value")
    if [[ $? == 0 ]]; then
      echo "$id_rsa" > terraform/ssh/gocd-${GOCD_ENVIRONMENT}
    else
      set -e
      ssh-keygen -f "terraform/ssh/gocd-${GOCD_ENVIRONMENT}" -q -N ""
    fi
    set -e
  fi
  chmod 0600 terraform/ssh/gocd-${GOCD_ENVIRONMENT}
  ssh-keygen -y -f "terraform/ssh/gocd-${GOCD_ENVIRONMENT}" > "terraform/ssh/gocd-${GOCD_ENVIRONMENT}.pub"
  aws ssm put-parameter \
   --region $AWS_REGION \
   --name $secret_id \
   --type SecureString \
   --overwrite \
   --value "`cat terraform/ssh/gocd-${GOCD_ENVIRONMENT}`"
}

function create_secret_ssm_param {
  secret_id="$1"
  value="$2"
  set +e
  aws ssm get-parameter --region $AWS_DEFAULT_REGION --name "$secret_id" | jq -r ".Parameter.Value" > /dev/null
  if [[ $? == 0 ]]; then
    echo "Secret at $secret_id already exists"
  else
    set -e
    echo "Secret does not exists. Creating $secret_id"
    aws ssm put-parameter \
     --region $AWS_DEFAULT_REGION \
     --name "$secret_id" \
     --type SecureString \
     --overwrite \
     --value "$value"
  fi
}

function generate_secret_ssm_param {
  value=$(openssl rand -base64 24  | tr -d "/@\'+")
  create_secret_ssm_param "$1" "$value"
}

command="$1"
case "${command}" in
  _ssh_key)
      check_gocd_env
      generate_ssh_key
      ;;
  ssh_key)
      check_gocd_env
      dojo "./tasks _ssh_key"
      ;;
  tf)
      check_gocd_env
      ./tasks ssh_key
      dojo "bash"
      ;;
  _tf_plan)
      tf_plan "$2"
      ;;
  tf_plan)
      check_gocd_env
      ./tasks ssh_key
      dojo "./tasks _tf_plan $2"
      ;;
  _tf_plan_agents)
      tf_plan "$2" "-target module.local-agents.aws_instance.gocd_agent"
      ;;
  tf_plan_agents)
      check_gocd_env
      ./tasks ssh_key
      dojo "./tasks _tf_plan_agents $2"
      ;;
  _tf_plan_server)
      tf_plan "$2" "-target aws_instance.gocd_server"
      ;;
  tf_plan_server)
      check_gocd_env
      ./tasks ssh_key
      dojo "./tasks _tf_plan_server $2"
      ;;
  _tf_apply)
      tf_apply
      ;;
  tf_apply)
      check_gocd_env
      ./tasks ssh_key
      dojo "./tasks _tf_apply"
      ;;
  _provision)
    check_gocd_env
    sudo pip install yasha #FIXME: add yasha in the dojo image
    scp -i terraform/ssh/gocd-${GOCD_ENVIRONMENT} terraform/bootstrap.sh ec2-user@${GOCD_ENVIRONMENT}.gocd.patient-deductions.nhs.uk:~
    ssh -i terraform/ssh/gocd-${GOCD_ENVIRONMENT} ec2-user@${GOCD_ENVIRONMENT}.gocd.patient-deductions.nhs.uk 'sudo ~/bootstrap.sh'
    yasha --variables terraform/tf-out-${GOCD_ENVIRONMENT}.json -o ansible/inventory/${GOCD_ENVIRONMENT}.ini ansible/inventory/template.ini.j2
    mkdir -p ansible/group_vars
    cat << EOF > ansible/group_vars/${GOCD_ENVIRONMENT}.yml
# This file is generated
env: ${GOCD_ENVIRONMENT}
EOF
    sudo ansible-playbook -i ansible/inventory/${GOCD_ENVIRONMENT}.ini ansible/site.yml
    ;;
  provision)
    check_gocd_env
    dojo -c Dojofile-ansible "./tasks _provision"
    ;;
  _create_secrets)
      generate_secret_ssm_param "/repo/${GOCD_ENVIRONMENT}/user-input/gocd-db-password"
      generate_secret_ssm_param "/repo/${GOCD_ENVIRONMENT}/user-input/gocd-db-username"
      ;;
  create_secrets)
      check_gocd_env
      dojo "./tasks _create_secrets"
      ;;
  generate_ssl_certs)
    check_gocd_env
    docker run -ti --rm -v $PWD/letsencrypt:/etc/letsencrypt \
     -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
     -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
     -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN  \
     certbot/dns-route53:v0.38.0 certonly \
     --keep-until-expiring  --register-unsafely-without-email \
     --dns-route53 --agree-tos  \
     -d ${GOCD_ENVIRONMENT}.gocd.patient-deductions.nhs.uk
    ;;
  sync_certs)
    check_gocd_env
    scp -i terraform/ssh/gocd-${GOCD_ENVIRONMENT} -r letsencrypt "ec2-user@${GOCD_ENVIRONMENT}.gocd.patient-deductions.nhs.uk:~/letsencrypt"
    ssh -i terraform/ssh/gocd-${GOCD_ENVIRONMENT} ec2-user@${GOCD_ENVIRONMENT}.gocd.patient-deductions.nhs.uk "sudo cp -r ~/letsencrypt /etc"
    ;;
  _test_assume_role)
    check_nhs_env
    AWS_ACCOUNT_ID=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/user-input/external/aws-account-id")
    aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/repository-ci-agent --role-session-name "$BUILD_TRACE_ID" > /dev/null
    ;;
  test_assume_role)
    dojo "./tasks _test_assume_role"
    ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
