format_version: 4
pipelines:
  agent-maintenance:
    group: gocd
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - disk-checks:
          approval: manual
          clean_workspace: true
          resources:
            - maintenance
          run_instances: all
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - df -h
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - "docker images | sort -k7 -h"
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - "docker container ls --all --format 'table {{.ID}}\t{{.Size}}' | sort -k2 -h"
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - "du -h --max-depth 3 /godata  | sort -k1 -h"
      - docker-cleanup:
          approval: manual
          clean_workspace: true
          resources:
            - maintenance
          run_instances: all
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - docker system prune --force
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - df -h
