format_version: 4
pipelines:
  "prm-gocd-infra":
    group: gocd
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - dev:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: dev
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                    - -c
                    - ./tasks test_assume_role
      - test:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: test
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                    - -c
                    - ./tasks test_assume_role
      - test:
          clean_workspace: true
          resources:
            - docker
          environment_variables:
            NHS_ENVIRONMENT: pre-prod
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                    - -c
                    - ./tasks test_assume_role
